//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using KeLi.HelloLinq2Db.SQLite.TableModels;

using LinqToDB;
using LinqToDB.Configuration;

namespace DataModels
{
	/// <summary>
	/// Database       : MyDatabase
	/// Data Source    : MyDatabase
	/// Server Version : 3.32.1
	/// </summary>
	public partial class MyDatabaseDB : LinqToDB.Data.DataConnection
	{
		public ITable<Person> People { get { return this.GetTable<Person>(); } }

		public MyDatabaseDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MyDatabaseDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MyDatabaseDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}
}

#pragma warning restore 1591
